[tool.poetry]
name = "methopt"
version = "0.1.0"
description = ""
authors = ["Eloof <t.vlasov23@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "1.25"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
